# Generated by Django 4.1.5 on 2023-01-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('surname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('image', models.ImageField(upload_to='', verbose_name='media/authors')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('orig_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (оригинал)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='media/books', verbose_name='Обложка')),
                ('day_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за день')),
                ('year', models.IntegerField(verbose_name='Год издания')),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('pages', models.IntegerField(verbose_name='Страниц')),
                ('author', models.ManyToManyField(to='books.author', verbose_name='Автор(ы)')),
                ('genre', models.ManyToManyField(to='books.genre', verbose_name='Жанры')),
            ],
        ),
    ]
