# Generated by Django 4.1.5 on 2023-02-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=128, verbose_name='Фамилия читателя')),
                ('name', models.CharField(max_length=128, verbose_name='Имя читателя')),
                ('patronymic', models.CharField(blank=True, max_length=128, null=True, verbose_name='Отчество')),
                ('passport_number', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Номер паспорта')),
                ('birth_date', models.DateField(verbose_name='Год рождения')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
            ],
        ),
    ]
